### ISSUE TITLE
essh is not available

### ISSUE THREAD

**Issue by stardiviner** [kaz-yos/eval-in-repl#10]
I found there is one line `(essh-next-code-line)` in `eir-eval-in-ruby` definition.
But I have not found `essh` in Emacs library. And there there is no this package in MELPA.

**Comment by kaz-yos** [comment]
It is available at the URL below. But since I am using only one function from this package, I should probably just incorporate the function into eval-in-repl to reduce dependencies.

http://www.emacswiki.org/emacs/essh.el

**Comment by stardiviner** [comment]
good choice.

**Comment by kaz-yos** [comment]
I incorporated the function as ```eir-next-code-line``` and dropped the ```essh.el``` dependency in version 0.8.0.
