### ISSUE TITLE
Don't hide other windows, only show two windows from eir.

### ISSUE THREAD

**Issue by stardiviner** [kaz-yos/eval-in-repl#13]
I found eval-in-repl will hide other windows, only show two windows, one is the source code buffer, and the other is the repl buffer. Sometimes I open many buffers, this behavior is bad. I have to open those buffers again, and I even can't remember which buffers I opened.
It has one benifit, it's clear.
I think this might need an option to toggle this behavior?

**Comment by kaz-yos** [comment]
Thanks for your suggestion. I should definitely include that option in the next release.

For the time being, a quick fix when that happens is to do ```(winner-undo)``` to restore the previous window configuration. 

Another hack you could do is to comment out the following line in the code. I haven't tried it myself so there my be unwanted complications.

https://github.com/kaz-yos/eval-in-repl/blob/f395ca4dcbee4c421d3fe1e75a2a74fcd6cd3089/eval-in-repl.el#L120

**Comment by stardiviner** [comment]
Thanks

**Comment by stardiviner** [comment]
I can add a `defcustom` variable `eir-delete-other-windows`. And add code:
```lisp
(if eir-delete-other-windows
  (delete-other-windows))
```

Should I add a pull request? Or need to improve this code?

**Comment by kaz-yos** [comment]
I can do that. Let me try that out with other supported languages, first.

**Comment by stardiviner** [comment]
You're right.

**Comment by kaz-yos** [comment]
I've created a branch to experiment with this. This kind of works, but at the first invocation of C-RET, now REPL window appears, at the second invocation of C-RET a random window (the window emacs chooses by ```other-window```, I believe) becomes the REPL. Being able to choose which window to turn into a REPL window is ideal. I'll think about how to implement that.

https://github.com/kaz-yos/eval-in-repl/commit/62a48bd579faca7383fdb8cf4ea1ef0ee9b09a55

**Comment by stardiviner** [comment]
The function `pop-to-buffer` might can be used for the REPL buffer. Because it can config the window display rules, and supported by other extensions like popwin: https://github.com/m2ym/popwin-el/

**Comment by kaz-yos** [comment]
I just updated the package so that the window configuration is minimally disturbed by C-RET.

- Only 1 window: Splitting occurs. For some languages (IELM, Python, Hy, shell, currently) which side the REPL takes can be configured.
- 2 windows: The other window becomes the REPL.
- 3+ windows: For the same languages stated above ```ace-window``` interface allows choosing which window to replace with the REPL. For other languages, it up to their major/minor modes' implementation.

**Comment by stardiviner** [comment]
1. Why the new behavior will use one exist window as position, instead of open a new window?
2. why by default `<C-return>` will try to send code to inferior? (this is not a good behavior).

**Comment by kaz-yos** [comment]
1. That may be a better behavior in some settings. I'll consider incorporating that.

2. This is the default behavior of the Emacs Speaks Statistics (ESS) package. The very reason of developing this package was to emulate this behavior. Keeping track of both expressions and evaluation results in the REPL buffer is what I am designing this package to do.

**Comment by stardiviner** [comment]
2. I see.

**Comment by stardiviner** [comment]
2. I see.
