### ISSUE TITLE
Deselect region after eval

### ISSUE THREAD

**Issue by tuhdo** [kaz-yos/eval-in-repl#14]
Currently, mark is always active after an expression is evaluated. We should restore the mark to its original state. That is, when `mark-active` is `nil` at the beginning, always restore it back afterward.

**Comment by kaz-yos** [comment]
Hi, thanks for your interest in the package. Which version of emacs and language are you using? The behavior may have changed in emacs version 25.

**Comment by tuhdo** [comment]
I'm using Emacs 25 with the latest version from MELPA.

**Comment by kaz-yos** [comment]
I just pushed a new version that should solve this problem. Please update and check if it solves your issue.

**Comment by Wilfred** [comment]
Works for me! :)

**Comment by kaz-yos** [comment]
Thanks for you input @Wilfred !
