### ISSUE TITLE
eval-in-repl-ruby error

### ISSUE THREAD

**Issue by diadochos** [kaz-yos/eval-in-repl#22]
When I execute `M-x eir-eval-in-ruby` in a ruby buffer with an `inf-ruby` mode, it gives the following error.
```
eir-send-to-repl: Wrong number of arguments: (lambda (command &optional name) "Run an inferior Ruby process, input and output in a new buffer.

The consecutive buffer names will be:
`*NAME*', `*NAME*<2>', `*NAME*<3>' and so on.

NAME defaults to \"ruby\".

Runs the hooks `comint-mode-hook' and `inf-ruby-mode-hook'.

(Type \\[describe-mode] in the process buffer for the list of commands.)" (setq name (or name "ruby")) (let ((commandlist (split-string-and-unquote command)) (buffer (current-buffer)) (process-environment process-environment)) (setenv "PAGER" (executable-find "cat")) (set-buffer (apply (quote make-comint-in-buffer) name (generate-new-buffer-name (format "*%s*" name)) (car commandlist) nil (cdr commandlist))) (inf-ruby-mode) (ruby-remember-ruby-buffer buffer) (setq inf-ruby-buffers (cons (current-buffer) inf-ruby-buffers)) (setq inf-ruby-buffer-impl-name name inf-ruby-buffer-command command)) (pop-to-buffer (setq inf-ruby-buffer (current-buffer)))), 0
```
However, `M-x ruby-send-region` works correctly.
Has there been an incompatible update recently?

Sorry to bother, but it would be awesome if you could look into this (I will try to fix this after the new years when I get the time).

**Comment by kaz-yos** [comment]
Thanks for reporting. I'll check this out.

**Comment by kaz-yos** [comment]
Hi, I'm sorry for the late response.

It looks like ```inf-ruby.el``` was updated to make ```run-ruby``` function to take a required command argument. I updated ```eval-in-repl``` (0.9.6) to use the  ```inf-ruby``` function, which seems to retain the behavior I want.

https://github.com/nonsequitur/inf-ruby/commit/ac80ea9fd35f14c0f7048445de2fc9b77a7f3cee#diff-b0fc04c71e57cf68de683676a95141e8L324
