### ISSUE TITLE
Make "jump to the next top form" optional

### ISSUE THREAD

**Issue by arichiardi** [kaz-yos/eval-in-repl#4]
As you wrote in your README, when developing, the workflow is to have code on one side and evaluate the changes of your functions in the repl.

I find not very useful to jump to the next form every time that you evaluate, and I would like to ask if possible to make it optional through a ```defcustom``` so that it can be set to false (can be left on by default so we don't break the current behaviour).

Thank you for this wonderful addition, I was waiting for and when I found it I immediately share it on my twitter @richiardiandrea :smile:

**Comment by kaz-yos** [comment]
I implemented your suggested changes for lisp languages. Please see the closed pull request. Thank you so much for the contribution.

**Comment by arichiardi** [comment]
Thanks! I am closing this ok? (kaz-yos/eval-in-repl@227ac85230f01379ac9175b649073a330477005e)
