### ISSUE TITLE
Geiser buffers changed names. 

### ISSUE THREAD

**Issue by nicolas-graves** [kaz-yos/eval-in-repl#52]
Some commits in the past years have changed the way Geiser REPL buffers are named, see for instance https://github.com/emacsmirror/geiser/commit/f9a40fe67e15ad2ec984687a8e99844707f736e5 
or https://github.com/emacsmirror/geiser/commit/47b378367169c3de160600e28ab08820a6d4b49f

The issue could be fixed simply by editing the regexp function, I'll do this in a pull request.

**Comment by kaz-yos** [comment]
Thanks!
