### ISSUE TITLE
add support for JavaScript

### ISSUE THREAD

**Issue by stardiviner** [kaz-yos/eval-in-repl#9]
there is a package called `js-comint` can do `inferior-js-mode` and `run-js`.
Hope you can support JavaScript.

**Comment by kaz-yos** [comment]
I'll consider this.

**Comment by stardiviner** [comment]
I implemented one, I will send a pull request, can you review it?

**Comment by kaz-yos** [comment]
Cool. Please do so. I might need some time since I'm a little busy for the next two weeks.

**Comment by stardiviner** [comment]
https://github.com/kaz-yos/eval-in-repl/pull/12

**Comment by kaz-yos** [comment]
Included in version 0.8.0.
